/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import necessary packages and classes
package component_toolbox_app;

import java.awt.BasicStroke;
import java.awt.Font;
//import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javafx.scene.paint.Color;

/**
 *
 * @author Oluwole_Jnr
 */
public class CapacitorColourBandView extends javax.swing.JPanel {

    /**
     * Creates new form CapacitorColourBandView
     */
    public CapacitorColourBandView() {
        initComponents();
        Controller control = Controller.getControllerObject();

        //Initialize View/Display
        control.initializeTantalumView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        band1Combo = new javax.swing.JComboBox<>();
        band2Combo = new javax.swing.JComboBox<>();
        band4Combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        band3Combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        resultLabel.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        resultLabel.setText("NA");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("BAND COLOUR'S SELECTER"));

        band1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        band1Combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                band1ComboItemStateChanged(evt);
            }
        });
        band1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band1ComboActionPerformed(evt);
            }
        });

        band2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        band2Combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                band2ComboItemStateChanged(evt);
            }
        });

        band4Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        band4Combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                band4ComboItemStateChanged(evt);
            }
        });

        jLabel2.setText("FIRST BAND");

        jLabel3.setText("SECOND BAND");

        band3Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        band3Combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                band3ComboItemStateChanged(evt);
            }
        });

        jLabel4.setText("THIRD BAND");

        jLabel5.setText("FOURTH BAND");

        jLayeredPane1.setLayer(band1Combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(band2Combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(band4Combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(band3Combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(band2Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band4Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(band3Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(band1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(band2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(band3Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(band4Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("CAPACITOR COLOUR BAND VALUE CALCULATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Edit the paint component in order to be able to draw customized images 
    //on the view
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        Controller control = Controller.getControllerObject();
        Model model = Model.getModelObject();

        //x and y movement cordinates will help shift any of the drawn diagrams easily
        //when the need srises
        int xMovement = 0;
        int yMovement = 0;

        //Create thick lines and draw the capacitor
        g2d.setStroke(new BasicStroke(20.0f));
        g2d.setColor(control.getAWTColourVersion(Color.BLACK));
        g2d.drawRoundRect(xMovement + 600, yMovement + 100, 150, 120, 30, 30);

        g2d.drawLine(xMovement + 625, 220, xMovement + 625, 260);
        g2d.drawLine(xMovement + 725, 220, xMovement + 725, 260);

        //Label the capacitor
        g2d.setColor(control.getAWTColourVersion(Color.ORANGE));
        g2d.setFont(new Font("Footlight MT Light", Font.BOLD, 25));
        g2d.drawString("TANTALUM CAPACITOR", xMovement + 540, yMovement + 295);

        g2d.setColor(control.getAWTColourVersion(model.getTantalumBand1Colour()));
        g2d.fillRoundRect(xMovement + 600, yMovement + 100, 150, 40, 10, 10);
        g2d.setColor(control.getAWTColourVersion(model.getTantalumBand2Colour()));
        g2d.fillRoundRect(xMovement + 600, yMovement + 140, 150, 40, 10, 10);
        g2d.setColor(control.getAWTColourVersion(model.getTantalumBand4Colour()));
        g2d.fillRoundRect(xMovement + 600, yMovement + 180, 150, 40, 10, 10);

        //The circle is the band 3
        g2d.setColor(control.getAWTColourVersion(model.getTantalumBand3Colour()));
        g2d.fillOval(645, 130, 60, 60);

        //PERFORM INSTANT CALCULATION
        control.triggerCapacitorCalculator();
        resultLabel.setText(model.getCurrentCapacitanceResult());

    }
    private void band1ComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_band1ComboItemStateChanged
        //If the band combo box item selection is changed, then
        //Automatically try to recalculate new capacitance value
        Controller control = Controller.getControllerObject();
        Model model = Model.getModelObject();
        int initState = model.getCapacitorViewInitFlag();
        Object obj = band1Combo.getSelectedItem();
        if ((obj != null) && (initState == 0)) {
            String selected = obj.toString();
            if (!selected.equals("NONE")) {
                Color selectedColourObject = control.getColourObject(selected);
                model.setTantalumBand1Colour(selectedColourObject);

                //Helps to refresh the view so that the change made to the 
                //colour bands of the tantalum capacitor can now be visible
                //by recalling the paint component
                Component_Toolbox_App.ccbv.repaint();
            }
        }
    }//GEN-LAST:event_band1ComboItemStateChanged

    private void band1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band1ComboActionPerformed

    }//GEN-LAST:event_band1ComboActionPerformed

    private void band2ComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_band2ComboItemStateChanged
        //If the band combo box item selection is changed, then
        //Automatically try to recalculate new capacitance value
        Controller control = Controller.getControllerObject();
        Model model = Model.getModelObject();
        int initState = model.getCapacitorViewInitFlag();
        Object obj = band2Combo.getSelectedItem();
        if ((obj != null) && (initState == 0)) {
            String selected = obj.toString();
            Color selectedColourObject = control.getColourObject(selected);
            model.setTantalumBand2Colour(selectedColourObject);

            //Helps to refresh the view so that the change made to the 
            //colour bands of the tantalum capacitor can now be visible
            //by recalling the paint component
            Component_Toolbox_App.ccbv.repaint();
        }
    }//GEN-LAST:event_band2ComboItemStateChanged

    private void band3ComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_band3ComboItemStateChanged
        //If the band combo box item selection is changed, then
        //Automatically try to recalculate new capacitance value
        Controller control = Controller.getControllerObject();
        Model model = Model.getModelObject();
        int initState = model.getCapacitorViewInitFlag();
        Object obj = band3Combo.getSelectedItem();
        if ((obj != null) && (initState == 0)) {
            String selected = obj.toString();
            Color selectedColourObject = control.getColourObject(selected);
            model.setTantalumBand3Colour(selectedColourObject);

            //Helps to refresh the view so that the change made to the 
            //colour bands of the tantalum capacitor can now be visible
            //by recalling the paint component
            Component_Toolbox_App.ccbv.repaint();
        }
    }//GEN-LAST:event_band3ComboItemStateChanged

    private void band4ComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_band4ComboItemStateChanged
        //If the band combo box item selection is changed, then
        //Automatically try to recalculate new capacitance value
        Controller control = Controller.getControllerObject();
        Model model = Model.getModelObject();
        int initState = model.getCapacitorViewInitFlag();
        Object obj = band4Combo.getSelectedItem();
        if ((obj != null) && (initState == 0)) {
            String selected = obj.toString();
            Color selectedColourObject = control.getColourObject(selected);
            model.setTantalumBand4Colour(selectedColourObject);

            //Helps to refresh the view so that the change made to the 
            //colour bands of the tantalum capacitor can now be visible
            //by recalling the paint component
            Component_Toolbox_App.ccbv.repaint();
        }
    }//GEN-LAST:event_band4ComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> band1Combo;
    public static javax.swing.JComboBox<String> band2Combo;
    public static javax.swing.JComboBox<String> band3Combo;
    public static javax.swing.JComboBox<String> band4Combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
