/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Load in necessary packages and classes
package component_toolbox_app;

import java.awt.BasicStroke;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javafx.scene.paint.Color;
import javax.swing.JButton;

/**
 *
 * @author Oluwole_Jnr
 */
public class ResistorColourBandView extends javax.swing.JPanel {

    /**
     * Creates new form ColourBandView
     */
    public ResistorColourBandView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        band1Button = new javax.swing.JButton();
        band2Button = new javax.swing.JButton();
        band3Button = new javax.swing.JButton();
        band4Button = new javax.swing.JButton();
        band5Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        band1Label = new javax.swing.JLabel();
        band2Label = new javax.swing.JLabel();
        band3Label = new javax.swing.JLabel();
        band4Label = new javax.swing.JLabel();
        band5Label = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fourBandRadio = new javax.swing.JRadioButton();
        fiveBandRadio = new javax.swing.JRadioButton();
        resultLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 244, 244));

        band1Button.setBackground(new java.awt.Color(153, 153, 153));
        band1Button.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        band1Button.setForeground(new java.awt.Color(255, 153, 0));
        band1Button.setText("BAND 1");
        band1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band1ButtonActionPerformed(evt);
            }
        });

        band2Button.setBackground(new java.awt.Color(153, 153, 153));
        band2Button.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        band2Button.setForeground(new java.awt.Color(255, 153, 0));
        band2Button.setText("BAND 2");
        band2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band2ButtonActionPerformed(evt);
            }
        });

        band3Button.setBackground(new java.awt.Color(153, 153, 153));
        band3Button.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        band3Button.setForeground(new java.awt.Color(255, 153, 0));
        band3Button.setText("BAND 3");
        band3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band3ButtonActionPerformed(evt);
            }
        });

        band4Button.setBackground(new java.awt.Color(153, 153, 153));
        band4Button.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        band4Button.setForeground(new java.awt.Color(255, 153, 0));
        band4Button.setText("BAND 4");
        band4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band4ButtonActionPerformed(evt);
            }
        });

        band5Button.setBackground(new java.awt.Color(153, 153, 153));
        band5Button.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        band5Button.setForeground(new java.awt.Color(255, 153, 0));
        band5Button.setText("BAND 5");
        band5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band5ButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("COLOUR CODE VALUE CALCULATOR VIEW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        band1Label.setText("No Selection");

        band2Label.setText("No Selection");

        band3Label.setText("No Selection");

        band4Label.setText("No Selection");

        band5Label.setText("No Selection");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("BANDS"));

        fourBandRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fourBandRadio);
        fourBandRadio.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        fourBandRadio.setForeground(new java.awt.Color(255, 153, 0));
        fourBandRadio.setMnemonic('0');
        fourBandRadio.setText("4 BANDS");
        fourBandRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fourBandRadioItemStateChanged(evt);
            }
        });

        fiveBandRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fiveBandRadio);
        fiveBandRadio.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        fiveBandRadio.setForeground(new java.awt.Color(255, 153, 0));
        fiveBandRadio.setMnemonic('1');
        fiveBandRadio.setSelected(true);
        fiveBandRadio.setText("5 BANDS");

        jLayeredPane1.setLayer(fourBandRadio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fiveBandRadio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fourBandRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fiveBandRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourBandRadio)
                    .addComponent(fiveBandRadio))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        resultLabel.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        resultLabel.setText("NA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(band1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(band1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(band2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(band2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(band3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(band3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(band4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(band5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(band4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(band5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(band1Label)
                    .addComponent(band2Label)
                    .addComponent(band3Label)
                    .addComponent(band4Label)
                    .addComponent(band5Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(band4Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band3Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band2Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band1Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(band5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void band1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band1ButtonActionPerformed
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        model.setCurrentBand(1);
        ColourDialogueView cdv = new ColourDialogueView();
        cdv.setVisible(true);
    }//GEN-LAST:event_band1ButtonActionPerformed

    private void band2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band2ButtonActionPerformed
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        model.setCurrentBand(2);
        ColourDialogueView cdv = new ColourDialogueView();
        cdv.setVisible(true);
    }//GEN-LAST:event_band2ButtonActionPerformed

    private void band3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band3ButtonActionPerformed
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        model.setCurrentBand(3);
        ColourDialogueView cdv = new ColourDialogueView();
        cdv.setVisible(true);
    }//GEN-LAST:event_band3ButtonActionPerformed

    private void band4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band4ButtonActionPerformed
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        model.setCurrentBand(4);
        ColourDialogueView cdv = new ColourDialogueView();
        cdv.setVisible(true);
    }//GEN-LAST:event_band4ButtonActionPerformed

    private void band5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band5ButtonActionPerformed
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        model.setCurrentBand(5);
        ColourDialogueView cdv = new ColourDialogueView();
        cdv.setVisible(true);
    }//GEN-LAST:event_band5ButtonActionPerformed

    private void fourBandRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fourBandRadioItemStateChanged
        //Load and open the ColourDialogueView so that user can select the desired
        //colour
        Model model = Model.getModelObject();
        Controller control = new Controller();
        if (buttonGroup1.getSelection().getMnemonic() == 48) { //4 bands selected
            band5Button.setEnabled(false);
            band5Label.setText("No Selection");
            model.setResistorBand5Colour(Color.IVORY);
            model.setFiveBands(false);
            //Refresh View
            Component_Toolbox_App.rcbv.repaint();
        } else {
            band5Button.setEnabled(true);
            model.setFiveBands(true);
        }
    }//GEN-LAST:event_fourBandRadioItemStateChanged

    //Refered to, to refresh the current view
    public void refreshView() {
        paintComponent(this.getGraphics());
    }

    //My customized paint component for the resistor colour band view
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g; //Taking charge of the graphics 
        //component this way will help facilitate the image drawing process

        Model model = Model.getModelObject();
        Controller control = Controller.getControllerObject();
        int xMovement = 0;
        int yMovement = 150;

        //Create Thick Band Lines
        g2d.setStroke(new BasicStroke(10.0f));

        //Band 1 Line
        g2d.setColor(control.getAWTColourVersion(model.getResistorBand1Colour()));
        g2d.drawLine(xMovement + 340, yMovement + 50, xMovement + 340, yMovement + 150);
        band1Button.setBackground(control.getAWTColourVersion(model.getResistorBand1Colour()));
        changeButtonForeground(band1Button, model.getResistorBand1Colour());
        band1Label.setText(control.getColourName(model.getResistorBand1Colour()));

        //Band 2 Line
        g2d.setColor(control.getAWTColourVersion(model.getResistorBand2Colour()));
        g2d.drawLine(xMovement + 390, yMovement + 50, xMovement + 390, yMovement + 150);
        band2Button.setBackground(control.getAWTColourVersion(model.getResistorBand2Colour()));
        changeButtonForeground(band2Button, model.getResistorBand2Colour());
        band2Label.setText(control.getColourName(model.getResistorBand2Colour()));

        //Band 3 Line
        g2d.setColor(control.getAWTColourVersion(model.getResistorBand3Colour()));
        g2d.drawLine(xMovement + 440, yMovement + 50, xMovement + 440, yMovement + 150);
        band3Button.setBackground(control.getAWTColourVersion(model.getResistorBand3Colour()));
        changeButtonForeground(band3Button, model.getResistorBand3Colour());
        band3Label.setText(control.getColourName(model.getResistorBand3Colour()));

        //Band 4 Line
        g2d.setColor(control.getAWTColourVersion(model.getResistorBand4Colour()));
        g2d.drawLine(xMovement + 490, yMovement + 50, xMovement + 490, yMovement + 150);
        band4Button.setBackground(control.getAWTColourVersion(model.getResistorBand4Colour()));
        changeButtonForeground(band4Button, model.getResistorBand4Colour());
        band4Label.setText(control.getColourName(model.getResistorBand4Colour()));

        //Band 5 Line
        g2d.setColor(control.getAWTColourVersion(model.getResistorBand5Colour()));
        g2d.drawLine(xMovement + 540, yMovement + 50, xMovement + 540, yMovement + 150);
        band5Button.setBackground(control.getAWTColourVersion(model.getResistorBand5Colour()));
        changeButtonForeground(band5Button, model.getResistorBand5Colour());
        band5Label.setText(control.getColourName(model.getResistorBand5Colour()));

        g2d.setStroke(new BasicStroke(10.0f));
        g2d.setColor(control.getAWTColourVersion(Color.BLACK));
        g2d.drawRoundRect(xMovement + 280, yMovement + 50, 330, 100, 70, 70);

        //Label Resistor
        g2d.setColor(control.getAWTColourVersion(Color.ORANGE));
        g2d.setFont(new Font("Footlight MT Light", Font.BOLD, 48));
        g2d.drawString("RESISTOR", xMovement + 330, yMovement + 195);

        g2d.setColor(control.getAWTColourVersion(Color.BLACK));
        g2d.drawLine(xMovement + 150, yMovement + 100, xMovement + 300, yMovement + 100);
        g2d.drawLine(xMovement + 590, yMovement + 100, xMovement + 740, yMovement + 100);
        g2d.fillOval(xMovement + 140, yMovement + 90, 20, 20);
        g2d.fillOval(xMovement + 740, yMovement + 90, 20, 20);

        //PERFORM INSTANT CALCULATION
        if ((model.getFiveBands() == true) && (model.getResistorBand1Colour() != Color.IVORY) && (model.getResistorBand2Colour() != Color.IVORY) && (model.getResistorBand3Colour() != Color.IVORY) && (model.getResistorBand4Colour() != Color.IVORY) && (model.getResistorBand5Colour() != Color.IVORY)) {
            control.triggerResistorCalculator("FIVE");
        } else if ((model.getFiveBands() == false) && (model.getResistorBand1Colour() != Color.IVORY) && (model.getResistorBand2Colour() != Color.IVORY) && (model.getResistorBand3Colour() != Color.IVORY) && (model.getResistorBand4Colour() != Color.IVORY)) {
            control.triggerResistorCalculator("FOUR");
        }
        resultLabel.setText(model.getCurrentResistanceResult());
    }

    //Mathod used to change the colour of the  'choose colour buttons'
    public void changeButtonForeground(JButton buttonReceived, Color bandColourReceived) {
        Model model = Model.getModelObject();
        Controller control = Controller.getControllerObject();
        if ((bandColourReceived != Color.WHITE) && (bandColourReceived != Color.IVORY)) {
            buttonReceived.setForeground(java.awt.Color.white);

        } else {
            buttonReceived.setForeground(control.getAWTColourVersion(Color.ORANGE));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton band1Button;
    private javax.swing.JLabel band1Label;
    private javax.swing.JButton band2Button;
    private javax.swing.JLabel band2Label;
    private javax.swing.JButton band3Button;
    private javax.swing.JLabel band3Label;
    private javax.swing.JButton band4Button;
    private javax.swing.JLabel band4Label;
    private javax.swing.JButton band5Button;
    private javax.swing.JLabel band5Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fiveBandRadio;
    private javax.swing.JRadioButton fourBandRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
